export const API_FUNCTIONS_ORDER = [
	"enableDevPanel",
	"utils",
	"siteComponents",
	"storeRouter",
	"storeIcons",
	"storeStyles",
	"storeData",
	"storeCard",
	"storeEditor",
	"storeReadme",
	"nextStoreNav",
	"nextStorePage",
	"ugcShareButton",
	"downloadButton",
	"listenAlongPanel",
	"toasts",
	"filePatch",
	"player",
	"customTracks",
	"playerColor",
];

export const API_FUNCTION_SUBMODULES = {
	listenAlongPanel: [
		"icons",
		"roster",
		"trackWidget",
		"chat",
		"roomList",
		"authGate",
		"infoModal",
		"index",
	],
};
