allowBuilds:
  "@parcel/watcher": true
  electron-winstaller: true
  esbuild: true
nodeLinker: hoisted
enableGlobalVirtualStore: false
storeDir: /home/admin/.local/share/pnpm/store/v11
verifyDepsBeforeRun: false
